   -- 1. How many transactions are recorded in the dataset?

   SELECT 
    COUNT(*) AS total_transactions
FROM
    sales;
   

-- 2.  How many unique customers made purchases?

   
  SELECT 
    COUNT(DISTINCT customer_id) AS total_customers
FROM
    sales;
   

-- 3.   What is the total sales revenue?

   
  SELECT 
    SUM(total_sale) AS total_revenue
FROM
    sales;

-- 4.    What is the average sale amount per transaction?

  SELECT 
    AVG(total_sale) AS avg_sale_per_transaction
FROM
    sales;



--   5.  Find total and average sales for each product category.

   SELECT 
    category,
    SUM(total_sale) AS total_sales,
    AVG(total_sale) AS avg_sales
FROM
    sales
GROUP BY category;
   

--   6.  Compare total sales between male and female customers.

   SELECT 
    gender, SUM(total_sale) AS total_sales
FROM
    sales
GROUP BY gender;
   

--   7.  List the top 5 transactions by total sale value.

   
  SELECT 
    *
FROM
    sales
ORDER BY total_sale DESC
LIMIT 5;
   

  --  8.  How many units were sold in each category?

   
  SELECT 
    category, SUM(quantity) AS total_quantity
FROM
    sales
GROUP BY category;




--   9.  What are the total sales for each day?

SELECT 
    sale_date, SUM(total_sale) AS daily_sales
FROM
    sales
GROUP BY sale_date
ORDER BY sale_date;
   

--     10.  Which hour of the day has the highest sales?

    SELECT 
    HOUR(sale_time) AS sale_hour, SUM(total_sale) AS total_sales
FROM
    sales
GROUP BY HOUR(sale_time)
ORDER BY total_sales DESC;
    




--    11. Find the average age of customers who purchased from each category.

    SELECT 
    category, AVG(age) AS avg_customer_age
FROM
    sales
GROUP BY category;
    

    -- 12.  Group customers by age range (e.g., 18–25, 26–35, etc.) 
    -- and calculate total sales.

    SELECT 
    CASE
        WHEN age BETWEEN 18 AND 25 THEN '18-25'
        WHEN age BETWEEN 26 AND 35 THEN '26-35'
        WHEN age BETWEEN 36 AND 45 THEN '36-45'
        WHEN age BETWEEN 46 AND 60 THEN '46-60'
        ELSE '60+'
    END AS age_group,
    SUM(total_sale) AS total_sales
FROM
    sales
GROUP BY age_group;


--    13.  Calculate profit for each transaction (assuming `total_sale - cogs`).

    
    SELECT 
    transactions_id, (total_sale - cogs) AS profit
FROM
    sales;
    

--   14. → Find the total profit generated by each category.

    SELECT 
    category, SUM(total_sale - cogs) AS total_profit
FROM
    sales
GROUP BY category;
    

--   15. → Which categories generate the highest profit?

   SELECT 
    category, SUM(total_sale - cogs) AS total_profit
FROM
    sales
GROUP BY category
ORDER BY total_profit DESC
LIMIT 3;
    

